### PR TITLE
day_3_ branch

### PR DESCRIPTION
**Pull request by kenlofgren**

### CODE REVIEW

**Comment by ryekerjh** [comment]
@kenlofgren I don't see your media queries in your .css file. A great resource for learning these can be found at http://www.w3schools.com/cssref/css3_pr_mediaquery.asp. So add those media queries locally, git add, git commit, and git push the changes, then go ahead and close this Pull Request. Good work!

**Comment by kenlofgren** [comment]
@ryekerjh Ok, I think I fixed it.

**Comment by ryekerjh** [comment]
@kenlofgren I'm still not seeing your media queries. It may be because you already merged into master but I didn't see them in your master branch either.

**Comment by kenlofgren** [comment]
That's funny, they are in the CSS last night.  I'll look at it again

**Pull request merged**
